require 'rake/testtask'

task :default => :test

Rake::TestTask.new :test do |t|
  t.libs << 'test'
  t.pattern = 'test/**/test_*.rb'
end


namespace :elm do
  desc "Compile Elm"
  task :compile do
    Dir.chdir("elm") do
      sh "elm-make ProblemVisualizer.elm --output ../javascripts/problemvisualizer.js"
      sh "elm-make SolutionVisualizer.elm --output ../javascripts/solutionvisualizer.js"
    end
  end
end
